<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./static/shirt.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Polo_Shirt001: THREE.SkinnedMesh
      root: THREE.Bone
      ['MCH-torsoparent']: THREE.Bone
      ['MCH-hand_ikparentL']: THREE.Bone
      ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
      ['MCH-hand_ikparentR']: THREE.Bone
      ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
      ['MCH-foot_ikparentL']: THREE.Bone
      ['MCH-thigh_ik_targetparentL']: THREE.Bone
      ['MCH-foot_ikparentR']: THREE.Bone
      ['MCH-thigh_ik_targetparentR']: THREE.Bone
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  export const gltf = useGltf<GLTFResult>('/shirt.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T is={gltf.nodes.root} />
    <T is={gltf.nodes['MCH-torsoparent']} />
    <T is={gltf.nodes['MCH-hand_ikparentL']} />
    <T is={gltf.nodes['MCH-upper_arm_ik_targetparentL']} />
    <T is={gltf.nodes['MCH-hand_ikparentR']} />
    <T is={gltf.nodes['MCH-upper_arm_ik_targetparentR']} />
    <T is={gltf.nodes['MCH-foot_ikparentL']} />
    <T is={gltf.nodes['MCH-thigh_ik_targetparentL']} />
    <T is={gltf.nodes['MCH-foot_ikparentR']} />
    <T is={gltf.nodes['MCH-thigh_ik_targetparentR']} />
    <T.SkinnedMesh
      geometry={gltf.nodes.Polo_Shirt001.geometry}
      material={gltf.materials['Material.001']}
      skeleton={gltf.nodes.Polo_Shirt001.skeleton}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
